# Generated by Django 2.2.7 on 2019-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalpataruapp', '0002_auto_20191208_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
